### ISSUE TITLE
Issue regarding evaluation of diffpool

### ISSUE THREAD

**Issue by ChenYizhu97** [FilippoMB/The-expressive-power-of-pooling-in-GNNs#2]
https://github.com/FilippoMB/The-expressive-power-of-pooling-in-GNNs/blob/ef5025422346d2fd45f0e8c462502f47a892b269/scripts/nn_model.py#L55

Hi FilippoMB,

I found the codes regarding evaluation of diffpool may not be implemented properly. In the paper, the assignment matrix is learnt by a GNN layer while the codes referred above learn the assignment by an MLP layer.

**Comment by FilippoMB** [comment]
Hi,

That should not matter.
The essence of diffpool and what sets it apart from other similar methods such as mincutpool and dmon is contained in the "dense_diff_pool", which is the auxiliary losses and the computation of the pooled graph.

In my implementation there is a GNN layer and a linear layer between the input features x and the pooling matrix s.
You are free to add more GNN and MLP layers in between, but then you have to add the same layers also to the other pooling methods, otherwise the change in performance you obtain depends on the capacity of the model not on the way pooling is implemented.

I hope this clarifies :)

**Comment by ChenYizhu97** [comment]
Hi FilippoMB, 

I could get what you mean. In the paper of diffpool, they use two GNNs. one is for updating the embedding X and another is for learning the assignment matrix S. I agree that we can just ignore the GNN for updaing the embedding X because we have the convolution part. However, I don't think the other GNN producing S could be just replaced by a linear layer.

In the code, the assignment matrix S of diffpool is learnt by

> S = Linear(X)

In the paper, the assignment matrix S of  diffpool is learnt by

> S = GNN(X, A)

I think these two ways are different, cause the later one learns the assignment matrix in GNN way, which we use the graph topology explicitly. The GNN here is not used for updating embedding but for learning assignment matrix. 
I think its different if we learn the assignment matrix by S=Linear(X). In this way, the edge of graph is not involved and we just treat the embedding as plain features.

Or maybe I think it wrong. I am not sure.

**Comment by FilippoMB** [comment]
I agree with you. It is different.

My point is that also mincut and dmon could use the same GNN to compute the s. At that point, it would be more difficult to say if the differences in performance (in good or worse) are due to that extra layer or to the more fundamental parts of the pooling operators. Note that would could have added also another GNN layer to compute the scores of top-K methods.

The purpose of the experiment was to change as little as possible in the underlying GNN architecture besides the pooling operation. Of course, like all experiments it is not perfect and some pooling methods might benefit more than others by using certain components before or after pooling. Nevertheless, it seemed to me the most fair and transparent way to compare each method.

**Comment by ChenYizhu97** [comment]
Hi FilippoMB,

I get your point now. I also agree the settings of the experiment is the most fair. I was just confused why It is a linear layer, which is slight different from the paper.  I don't think the difference influence the experiment either.

Thank you for the replies!
